---
# --- Metadatos Básicos ---
title: "Impacto de la adicción digital en el rendimiento académico y bienestar de los estudiantes en diferentes países"
author:
   - Michelle Salazar
   - José Hernández
   - Diego Guerrero
date: "Marzo 2026"

# --- Metadatos Específicos de Plantilla ---
degree: "Computación I"
director: 
  - Jesus Ochoa 
  - Oliver Triveño
lugar: "Caracas"
facultad: 
  - Facultad de Ciencias Económicas y Sociales
  - Escuela de Estadistica y Ciencias Actuariales
# Ruta al escudo (relativa al archivo .Rmd)
escudo: "Latex/Classes/Escudos/faces"

# --- Bibliografía ---
bibliography: bibliografia.bib

# --- Configuración de Salida ---
output: 
  pdf_document:
    template: template.tex  # Llamamos al archivo de plantilla
    keep_tex: true                 # Útil para ver errores si ocurren
    toc: true                      # Generar índice
    number_sections: true
    citation_package: natbib       # Importante: forzar natbib porque tu plantilla lo usa

# --- Resumen (Abstract) ---
abstract: |
  Resumen del trabajo de investigación...
---

```{r setup, include=FALSE}
# Configuración global de chunks
knitr::opts_chunk$set(
  echo = FALSE,        # Mostrar código
  warning = FALSE,    # Ocultar advertencias
  message = FALSE,    # Ocultar mensajes de carga
  fig.align = "center",
  out.width = "90%",
  fig.pos = "H",
  out.extra = ""
)

# Cargar librerías necesarias
library(tidyverse)
library(knitr)
library(kableExtra)
library(scales)
```

\chapter*{Introducción}

Introducción del trabajo de investigación

\chapter{Planteamiento del Problema}
Describir planteamiento del problema\ Desde su aparición las redes sociales cambiaron la manera en que las personas interactúan con el mundo real, desde servir como medios de comunicación hasta convertirse en plataformas que afectan el comportamiento del ser humano. En los estudiantes estas plataformas son útiles para acceder a información y conocer noticias mundiales. Sin embargo, el uso de las redes sociales se ha transformado en un fenómeno que crece a gran escala, la adicción a las redes, y la adicción al mundo digital.
El problema radica en que el uso de las redes y plataformas digitales puede llegar a un extremo de dependencia, e incluso excesiva en algunos casos. Siendo un factor que influye en los estudiantes y en su capacidad de concentración, afectando su rendimiento académico.
La gran mayoría de estudiantes tienen acceso a las diferentes plataformas de redes sociales, pero desconocemos su comportamiento a nivel geográfico y variables como el tipo específico de red social (TikTok, Instagram, WhatsApp, etc.) factores como la salud mental, o el entorno geográfico puede darnos ciertas “tendencias” sobre la dependencia a las redes sociales. Por esto, es necesario investigar si la adicción a las plataformas digitales y redes sociales se comporta de la misma manera en todo el mundo, o responde a  patrones específicos por región.

Argumento final. Debido a esto, se plantea las siguientes preguntas de investigación:\


\textbf{1.}	Pregunta1\ ¿Cómo se distribuyen los nivelees de adicción digital con dependencia significativamente alta? 

\textbf{2.}	Pregunta2\ ¿Los estudiantes comn mayores puntajes de adicción digital reportan mayor frecuencia que las redes solciales afectan negativamente en su rendimiento académico?

\textbf{3.}	Pregunta3\ ¿De que forma el uso de redes sociales especificas afecta la salud mental y reduce las horas de sueño de los estudiantes?

\textbf{5.}	Pregunta5\ ¿Cómo varían los niveles de adicción digital entre los diferentes países y qué patrones de riesgo nos permiten clasificar a los países según el impacto de ésta dependencia?


\section{Justificación}

Justificación del trabajo de investigación\ El proposito ce esta investigación es identificar los patrones y comportamientos del uso excesivo de las redes sociales, identificando que niveles significativos se encuentran y que relaciones tienen con la vida del estudiante, comprender que riesgos surguen en su rendimiento académico, problemas de salud mental y trastornos de sueño.
  Mediante éste análisis se busca cuantificar dichas problemáticas que lleven a aplicar estrategias y concientizar la prevención a la hora de usar redes sociales, logrando establecer una vida más saludable, productiva y equilibrada para los estudiantes en distintos países.

\section{Objetivos}
 
\subsection{Objetivo General}
\begin{itemize}
  \item{Analizar la adicción a las redes sociales y su impacto en el bienestar académico y mental de los estudiantes, comparando los patrones de comportamiento entre los diferentes países.}
\end{itemize}

\subsection{Objetivos Específicos}
\begin{itemize}
  \item{Describir la adicción estadística de los puntajes de adicción digital de los estudiantes mediante medidas de tendencia central y dispersión, para determinar si existen grupos con una dependencia significativamente alta}
  \item{Determinar la asociación entre el nivel de adicción digital y la percepción de como afecta el rendimiento academico para reconocer si los estuduantes con mayor dependencia reportan un imoacto negativo en sus estudios}
  \item{Determinar el impacto del uso de redes sociales en la salud mental y calidad de sueño de los estudiantes, identificando las redes sociales que afectan en mayor nivel}
  \item{Reconocer que plataformnas de redes sociales vincula con los niveles más bajos de salud mental y horas de sueño}
  \item{Identificar patrones geográficos de riesgo mediante la clasificación de países según sus niveles de adición permitiendo detectar tendencias regionales y variaciones significativas en el impacto de la dependencia digital. }
\end{itemize}


\section{Cobertura}

\subsection{Horizontal}

Describir la cobertura Horizontal del trabajo de investigación\

\begin{table}[ht]
\centering
\caption{Variables consideradas} 
\resizebox{10cm}{!} {
\begin{tabular}{ccc}
  \hline
\ \ \ \ \ NOMBRE DE LA VARIABLE \\ 
  \hline
   VARIABLE 1 \\ 
VARIABLE 2\\ 
VARIABLE n\\ 
   \hline
\end{tabular}
}
\end{table}

\subsection{Vertical}

Describir la cobertura Vertical del trabajo de investigación


\section{Periodo de Referencia}

Describir la fuente y el Periodo de Referencia utilizado en el trabajo de investigación

\section{Variables}

Describir la variable en estudio en el trabajo de investigación

\chapter{Marco Teórico}


\section{Bases Teóricas}

Resumen de las bases teoricas explicadas en el capitulo y su importancia\

\subsection{Definición 1}

Descripción de la definición 1\

\subsection{Definición 2}

Descripción de la definición 2\

\subsection{Definición n}

Descripción de la definición n\


\chapter{Marco Metódico}
En esta sección se presentan las metodologías y/o test necesarios relacionados con la práctica divulgada en el marco teórico, así como las fuentes de datos.
 
\section{Bases metódicas utilizadas en el trabajo de investigación}

Desarrollo\

\subsection{Item 1}

Descripción\

\subsection{Item 2}

Descripción\

\subsubsection{Item 2.2}

Descripción\

\subsection{Item n}

Descripción\

\chapter{Análisis de Resultados}

{\small Este capítulo presenta los resultados obtenidos al aplicar las metodologías descritas en el capítulo anterior, así como del análisis estadístico descriptivo de las variables estudiadas y las ventajas y desventajas al aplicar dichos tests.}

\section{Presentación de resultados 1}

Descripción\

\section{Presentación de resultados 2}

Descripción\

\section{Presentación de resultados n}

Descripción\

\chapter{Conclusiones y Recomendaciones}

\textbf{1.-} Conclusion 1 del trabajo de investigación.\

\textbf{Recomendación} 
Recomendación 1 del trabajo de investigación.\

\textbf{2.-} Conclusion 2 del trabajo de investigación.\

\textbf{Recomendación} 
Recomendación 2 del trabajo de investigación.\

\textbf{n.-} Conclusion n del trabajo de investigación.\

\textbf{Recomendación} Recomendación n del trabajo de investigación.\

\appendix
\renewcommand{\thechapter}{\Alph{chapter}}

\chapter{Anexo A}

\chapter{Anexo B}

\chapter{Anexo C}

